version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j9b64f9zd4cm"
s3_prefix = "testapp"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
